Montevideo:
  timezone:
    timezone_name: 'America/Montevideo'
  s3_path: 's3://wbg-waze/feed/UY/784montevideo'
  aws_profile: '' # your profile
  crs:
    projected_crs: 'EPSG:32721'
geographies:
    'admin2':
      name: 'Administrative Level 2'
      path: '../data/zonificacion-montevideo-region.gpkg'
      plot_by_geography: True
    'hex_id_7':
      name: 'Hexagons Level 7'
      path: '../data/montevideo-h7.gpkg'
      plot_by_geography: False
